arb-dir: lib/l10n
template-arb-file: app_zh.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - zh
  - en
nullable-getter: false
untranslated-messages-file: lib/l10n/untranslated.json
